sudo: false

language: go

arch:
    - amd64
    - arm64
go:
  - master

os:
  - linux

branches:
  only:
  - master

install:
  - chmod +x build-docs.sh

script:
  - ./build-docs.sh prerequisites
  - ./build-docs.sh ext-docs
  - ./build-docs.sh update-page all
  - ./build-docs.sh build
